name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Generate test results in machine format
        run: flutter test --machine > test-results.json

      - name: Display test results
        run: cat test-results.json

      - name: Check if test-results.json exists
        run: |
          if [ ! -f test-results.json ]; then
            echo "test-results.json not found!"
            exit 1
          fi

      - name: Validate JSON format
        run: |
          sudo apt-get install -y jq
          cat test-results.json | jq . > /dev/null
          if [ $? -ne 0 ]; then
            echo "Invalid JSON format in test-results.json"
            exit 1
          fi

      - name: Report test results
        uses: dorny/test-reporter@v1.9.1
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json

      - name: Report coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 0
