name: Dart Code Metrics

on:
  pull_request:
  push:
    branches:
      - developer

jobs:
  check:
    name: Dart Code Metrics

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Run Dart Code Metrics
        run: |
          dart pub global activate dart_code_metrics
          dart metrics lib --reporter=console
