name: Analyze Code

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  analyze:
    name: Analyze Code with Dart and Flutter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.0.3'

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze Dart Code
        run: dart analyze
